name: Liberacion continua
on:
  release:
    types: created
permissions:
  contents: write
jobs:
  compilar-y-liberar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
      - name: Compilar codigo
        run: gcc hola.c -o hola -O3
      - name: Subir el ejecutable
        uses: svenstaro/upload-release-action@v2
        with:
          file: hola
          repo_token: ${{ secrets.GITHUB_TOKEN }}
